persistence true
persistence_location /mosquitto/data/
autosave_interval 30
log_dest stdout
log_type error
log_type warning
log_type notice
allow_anonymous false
password_file /mosquitto/data/passwd
acl_file /mosquitto/config/acl
listener 1883
protocol mqtt
listener 9001
protocol websockets
socket_domain ipv4
persistent_client_expiration 1h
max_queued_messages 250000
max_queued_bytes 100000000
max_inflight_messages 40
